# Additional Data node in case StatefulSet was not used
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-data2
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: carlosedp/docker-elasticsearch-kubernetes:6.2.2-arm64
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: myesdb
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        #- name: "ES_PLUGINS_INSTALL"
        #  value: "x-pack"
        resources:
          limits:
            cpu: 1
        ports:
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 360
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config
          mountPath: /elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: elasticsearch-storage2
      - name : config
        configMap:
          name: es-configmap
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-storage2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

