apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      serviceAccount: elk
      containers:
      - name: kibana
        image: carlosedp/docker-kibana:6.2.2
        env:
        - name: KIBANA_ES_URL
          value: "http://elasticsearch:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: CLUSTER_NAME
          value: myesdb
        - name: SERVER_BASEPATH
          value: kibana.internal.carlosedp.com
        - name: "ES_PLUGINS_INSTALL"
          value: "x-pack"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
