apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-client
  namespace: logging
  labels:
    component: elasticsearch
    role: client
spec:
  serviceName: elasticsearch-logging
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-client
        image: carlosedp/docker-elasticsearch-kubernetes:6.2.2-arm64
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 2
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: myesdb
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: NETWORK_HOST
          value: _site_,_lo_
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        #- name: "ES_PLUGINS_INSTALL"
        #  value: "x-pack"
        livenessProbe:
         tcpSocket:
           port: http
         initialDelaySeconds: 360
         periodSeconds: 60
        readinessProbe:
         httpGet:
           path: /_cluster/health
           port: http
         initialDelaySeconds: 360
         timeoutSeconds: 60
        volumeMounts:
        - name: config
          mountPath: /elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: storage-client
          mountPath: /data
      volumes:
      - name : config
        configMap:
          name: es-configmap
  volumeClaimTemplates:
  - metadata:
      name: storage-client
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
