apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master
  namespace: logging
  labels:
    component: elasticsearch
    role: master
spec:
  serviceName: elasticsearch-logging
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-master
        image: carlosedp/docker-elasticsearch-kubernetes:6.2.2-arm64
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 2
        ports:
        - containerPort: 9300
          name: transport
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: myesdb
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        #- name: "ES_PLUGINS_INSTALL"
        #  value: "x-pack"
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 360
          periodSeconds: 30
        volumeMounts:
        - name: config
          mountPath: /elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: storage-master
          mountPath: /data
      volumes:
      - name : config
        configMap:
          name: es-configmap
  volumeClaimTemplates:
  - metadata:
      name: storage-master
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
