apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-events-printer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-events-printer
rules:
- apiGroups: [""]
  resources:
  - events
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-events-printer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-events-printer
subjects:
- kind: ServiceAccount
  name: kubernetes-events-printer
  namespace: monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-events-printer
  labels:
    component: fluentd
    role: kubernetes-events-printer
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        component: fluentd
        role: kubernetes-events-printer
    spec:
      serviceAccount: kubernetes-events-printer
      containers:
      - name: kubernetes-events-printer
        image: kayrus/kubernetes-events-printer:latest
        imagePullPolicy: Always
